#define IDI_APPICON                    101
#define IDR_MAINMENU                   102
#define IDR_ACCELERATOR                103
#define IDD_ABOUTDIALOG                104
#define IDD_MIDICHOOSER                105
#define IDD_ADDSUBTRACK                106
#define IDR_RMBMENU                    107
#define IDI_MIDI_OFF                   108
#define IDI_MIDI_ON                    109
#define IDI_LOOP                       110
#define IDI_PLAY                       111
#define IDI_PAUSE                      112
#define IDI_STOP                       113
#define IDI_LIST                       114
#define IDI_TEXT_NAME                  115
#define IDI_TEXT_START                 116
#define IDI_TEXT_STOP                  117
#define ID_FILE_EXIT                   40001
#define ID_HELP_ABOUT                  40002
#define ID_FILE_OPEN                   40003
#define ID_FILE_RELOAD                 40004
#define ID_FILE_MIDI                   40005
#define ID_PLAY                        40006
#define ID_PAUSE                       40007
#define ID_STOP                        40008
#define ID_REFRESH                     40009
#define ID_DEVICELIST                  40010
#define ID_TOGGLE                      40011
#define ID_QUIT                        40012
#define ID_MIDI_DEF                    40013
#define ID_TRACKS                      40014
#define ID_EXPAND                      40015
#define ID_EDIT_ADD                    40016
#define ID_EDIT_REMOVE                 40017
#define ID_EDIT_REMALL                 40018
#define ID_FILE_OPEN_T                 40019
#define ID_FILE_SAVE_T                 40020
#define ID_FILE_SAVE_TA                40021
#define ID_LOOP                        40022
#define ID_IDLE                        40023

#define CANCER                         40030
#define DEF_CANCER                     40031
#define ADD_STRACK                     40032
#define SWAP_STRACKS                   40033

#ifndef IDC_STATIC
  #define IDC_STATIC                   -1
#endif
